Feature/boolean slider
FlockOfBirds/boolean-slider pull request #1
Opened 2017-02-02 13:52 UTC by edwinmp

2017-02-02 14:35 UTC, Andries-Smit requested changes
Good quality code, last small steps before approval

2017-02-02 14:35 UTC, Andries-Smit commented on Gruntfile.js
> +    grunt.loadNpmTasks("grunt-contrib-copy");
Add dependency check

2017-02-02 14:35 UTC, Andries-Smit commented on karma.conf.js
> +        console.log("With instrumenter");
Remove console.log

2017-02-02 14:35 UTC, Andries-Smit commented on package.json
> +  "description": "Toggle a boolean attribute.",
Remove period.

2017-02-02 14:35 UTC, Andries-Smit commented on package.json
> +    "@types/react": "^15.0.4",
Update typing

2017-02-02 14:35 UTC, Andries-Smit commented on src/com/mendix/widget/BooleanSlider/BooleanSlider.ts
> +            ? !this.readOnly && !this.contextObject.isReadonlyAttr(this.booleanAttribute) ? "enabled" : "disabled"
Extract for readability
`const enabled = !this.readOnly && !this.contextObject.isReadonlyAttr(this.booleanAttribute);`

2017-02-02 14:35 UTC, Andries-Smit commented on src/com/mendix/widget/BooleanSlider/BooleanSlider.ts
> +                error: (error: Error) =>
Remove type `Error` it is defined in mendix-client typing `mx.ui.action`

2017-02-02 14:35 UTC, Andries-Smit commented on src/com/mendix/widget/BooleanSlider/components/Slider.ts
> +        props.alertMessage ? createElement(Alert, { message: props.alertMessage }) : null
Move condition to Alert component

2017-02-02 14:35 UTC, Andries-Smit commented on src/com/mendix/widget/BooleanSlider/components/Alert.ts
> +    DOM.div({ className: "alert alert-danger widget-boolean-slider-alert" }, props.message);
Add condition
```
export const Alert = (props: { message: string }) =>
    props.message 
        ? DOM.div({ className: "alert alert-danger widget-boolean-slider-alert" }, props.message)
        : null
```

2017-02-02 14:35 UTC, Andries-Smit commented on src/com/mendix/widget/BooleanSlider/components/__tests__/Alert.spec.ts
> +    });
Add test for condition no prop.message

2017-02-02 14:35 UTC, Andries-Smit commented on src/com/mendix/widget/BooleanSlider/components/Slider.ts
> +                "no-slider": props.status === "no-context"
Is this the correct name `no-slider`?

2017-02-02 16:23 UTC, Andries-Smit commented on src/com/mendix/widget/BooleanSlider/ui/Slider.sass
> +
Remove double white lines and spaces in the sass files

2017-02-03 07:40 UTC, edwinmp commented on package.json
> +  "description": "Toggle a boolean attribute.",
Done.

2017-02-03 07:54 UTC, edwinmp commented on src/com/mendix/widget/BooleanSlider/BooleanSlider.ts
> +            ? !this.readOnly && !this.contextObject.isReadonlyAttr(this.booleanAttribute) ? "enabled" : "disabled"
Done.

2017-02-03 07:54 UTC, edwinmp commented on src/com/mendix/widget/BooleanSlider/BooleanSlider.ts
> +                error: (error: Error) =>
Done.

2017-02-03 08:06 UTC, edwinmp commented on src/com/mendix/widget/BooleanSlider/components/Slider.ts
> +        props.alertMessage ? createElement(Alert, { message: props.alertMessage }) : null
Done.

2017-02-03 08:06 UTC, edwinmp commented on src/com/mendix/widget/BooleanSlider/components/Alert.ts
> +    DOM.div({ className: "alert alert-danger widget-boolean-slider-alert" }, props.message);
Done.

2017-02-03 08:13 UTC, edwinmp commented on src/com/mendix/widget/BooleanSlider/components/__tests__/Alert.spec.ts
> +    });
Done.

2017-02-03 08:14 UTC, edwinmp commented on src/com/mendix/widget/BooleanSlider/ui/Slider.sass
> +
Done.

2017-02-03 08:15 UTC, edwinmp commented on karma.conf.js
> +        console.log("With instrumenter");
Done.

2017-02-03 08:16 UTC, edwinmp commented on Gruntfile.js
> +    grunt.loadNpmTasks("grunt-contrib-copy");
Not sure what you meant here :)

2017-02-03 08:27 UTC, edwinmp commented on src/com/mendix/widget/BooleanSlider/components/Slider.ts
> +                "no-slider": props.status === "no-context"
Yup... A better suggestion?

2017-04-21 12:17 UTC, closed without merging